### PR TITLE
Added Homepage w/ HTML Functionality + CSS

### PR DESCRIPTION
**Pull request by AustonBoyd**
-Added HTML functionality and css to homepage, including;

> Buttons for game instructions

> New color scheme for buttons (hover)

> 'Instructions!' button currently utilizing a placeholder alert. (instructions display option still needed)

> 'Meet The Team' button acts as link to the team's Github repo

-Replaced 'Welcome' header to better match Figma mock-up

-Removed 'to page 2' text from body

-Removed 'PLAY!' hyperlink from body

-Removed 'Meet The Team' hyperlink from footer

### CODE REVIEW

**Review by chonger878 — APPROVED** [review]
Everything looks great.  Just curious, why not have a link to the github repo on every page of the site?  I might have missed something at the last meeting, sorry.

**Review by terrifricker — COMMENTED** [review]
**\<head> and \<header>**
There are two html elements that have almost the same name - \<head> and \<header>.  

The[ \<head>](https://www.w3schools.com/html/html_head.asp) contains information about the webpage itself,  "meta data".  It usually has the following information:

- \<title> \</title> *which you have*

- \<meta> tags such as

\<meta charset="utf-8"> *to tell the browser what character set is being used*
\<meta name="description" content="description of the website> * for seo purposes*
\<meta name="viewport" content="width=device-width, initial-scale=1.0"> *to allow use of viewport units*

- \<link rel="stylesheet" href="mystyle.css"> *link to the stylesheet*

and sometimes,

- \<script src="app.js" defer></script> *to link the javascript file*
*The link to the javascript file is also sometimes found as the last element in \<body> so it loads after the visible portions of the page have loaded.  Adding "defer" to the script tag in head accomplishes the same thing.  It defers loading until the visible elements in the body have loaded.*

All content that will be visible on the website goes in the \<body>.  So, your \<p> tag should be moved down into the body, most likely in an element [\<header>](https://www.w3schools.com/tags/tag_header.asp) because it is introductory information.

**Review by terrifricker — COMMENTED** [review]
**CSS Transitions**
Awesome that you are adding it!  Each transition needs at least two elements,
transition-property and transition-duration and they should be on the element that is being transitioned.  There are also transition-timing-function and transition-delay.  They can be written using the shorthand property transition with the syntax:

```
div {
  transition: <property> <duration> <timing-function> <delay>;
}
```
You can also use transition-property: all to target all of the properties that are changing.  So, you could add

`transition: all 0.4s;`

on each of your buttons.

**Simplifying CSS**
In fact, because so many of your button properties are the same, you can use a css class="button" to contain all of the rules that pertain to all of the buttons, adding that class to each of the buttons, for example
```
<button class="button button1" ....
```
Then in your css file, have 
```
.button {
    all the properties that are the same for each button, including 
    transition: all 0.4s;
}
```
Then each .button1, .button2, and .button3 with the properties that are specific to them.
```
looks like just their margin-left.

**Review by terrifricker — APPROVED** [review]
Even though I added comments, I'm going to approve this pull request as is BECAUSE it works!  My suggestions can be made later if wanted through refactoring.

**Pull request merged**
