### PR TITLE
Import json data for use in javascript file app.js

### LINKED ISSUE #49: Issue: Handle multiple stories and optimize how data is read and stored
## Acceptance Criteria

- [x] A user I must be able to experience at least five different madlib stories.

<br />
<br />

## Additional optimization 1: DRY ISSUE

- Using hard corded input variables to replace blanks on our stories could be  [DRY principles](https://en.wikipedia.org/wiki/Don%27t_repeat_yourself) problem

This issue is in reference to our current app.js
https://github.com/chingu-voyages/v43-tier1-team-08/blob/288a74d645e8f378254bc03b2b7e231ead889d46/app.js#L1-L24

- This approach can work for two stories, and even for five stories. 
- If possible, depending on how you wish to handle additional stories, the challenge here is, what are other ways could you handle additional stories without repeating this code 5 more times? Or is this good enough to go with?

## Helpful tips?

Looking for where to start to handle data dynamically? I would suggest implementing some datastructures like arrays or dictionaries to store stories, classify them, destructure, read and write to them and send that information to the DOM as needed.

1. Ex. Arrays of words

```js
const words = ["Word1", "Word2", "Word3"];
```

2. Here's an example of Javascript Objects (JSON) to strore parts of speech + categories

```js
 {
    "noun": ["food", "clothing", "a place", "a game", "animal", "room"],
    "adjective": ["a color", "-est", "-ous", "-able"],
    "verb": ["action", "passed tense", "ends in -ing"],
    "misc": ["a feeling"]
  }
```

> NOTE: I am not implying that the current approach doesn't work, rather, maybe re-name the variables to `input1` `input2` so that they can adapt any other format you give it. 

## Additional optimization 2: `innerHTML` security

https://github.com/chingu-voyages/v43-tier1-team-08/blob/288a74d645e8f378254bc03b2b7e231ead889d46/app.js#L39

- There are various ways to manipulate the DOM but worth thinking about the documented security issue with using `innerHMTL` to inject code into the HTML see [security coniderations](https://developer.mozilla.org/en-US/docs/Web/API/Element/innerHTML#security_considerations)

### Review

- The goal of this issue is to meet the acceptance criteria, and not to optimize the code
- If it's already working as expected, meeting additional optimization specs is not a requirement. 
- As long as it's working this issue will be closed.

### LINKED ISSUE #60: Import external json data for use in javascript file

### PR DESCRIPTION
**Pull request by terrifricker**
## Description
Rewrite app.js to import json from an external file using the fetch() api.  A new file data.json is created and stored in folder data.  It currently contains the data for a single story as json.  The json keys used are "title", "labels", "inputIds", and "storyPieces".  The fetch() api requests the data from the data/data.json file, and returns the data as a javascript object and calls a new function named "process(data)" on the data.  The code to process the story data has been moved inside this function.

## Related Issue

Closes #60 

## Acceptance Criteria

Upon opening the html file third.html, the title from data.json should appear as well as the form created from data.json.
After entering words into the form and clicking on the submit button, the story created from data.json and the user-entered words should appear.

## Type of Changes

|     | Type                       |
| --- | -------------------------- |
|     | :bug: Bug fix              |
| ✓   | :sparkles: New feature     |
|     | :hammer: Refactoring       |
|     | :100: Add tests            |
|     | :link: Update dependencies |
|     | :scroll: Docs              |

## Updates
Updates app.js, and adds file data.json in folder named 'data'

## UI/UX
No changes

### CODE REVIEW

**Comment by terrifricker** [comment]
I tried to separate things out into functions, but ran into a problem with the asynchronous eventListener.  My first idea was something like
```
function process(data) {
    addTitleToDOM(data)
    createForm(data)
    addFormToDOM(data)
    getUserEnteredWords(data)
    createStory(data)
    addStoryToDOM(data)
}
```

But then I needed to pass data around...
```
function process(data) {
    addTitleToDOM(data)
    let formHTML = createForm(data)
    addFormToDOM(formHTML)
    let words = getUserEnteredWords(data)
    let storyHTML = createStory(data, words)
    addStoryToDOM(storyHTML)
}
```

Once I was working on getUserEnteredWords, I struggled to pass the words back out because the words were gathered in the eventListener that takes time.  I read a little bit about 'async' and 'await' and figured it was easier to just put the story and adding it to the DOM back into the eventListener.

At that point, my function list was messed up since the last three became one function anyway.  I thought about simplifying to
```
function process(data) {
    title(data)
    form(data)
    story(data)
}
```  
but just gave up on making separate functions.  Now seeing it typed out, it doesn't seem too bad, especially because Deepali did a great job of pulling her game reset out into a function.

Any ideas  or suggestions?  Is this where react makes passing data back and forth easier?  What about how it works with asynchronous problems?

**Comment by terrifricker** [comment]
I also tried using [ES6 Modules](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Modules) to import the json data.  It worked in Chrome, but not Safari.

**Review by mmsaki — COMMENTED** [review]
Nice! Looks Great! We now have stories stored in data.json.

One thing though, is there a reason to use fetch instead of just doing an import? I'm sure both work, not sure about the use cases, if relevant to which method to use for imports?
```js
import data from './data/data.json'
```

**Comment by terrifricker** [comment]
I tried import and wasn't able to get it to work in Safari 16.3

**Pull request merged**
