### PR TITLE
master/project-website

### PR DESCRIPTION
**Pull request by mmsaki**

### CODE REVIEW

**Comment by terrifricker** [comment]
I didn't realize that this built a site.  I guess we need to talk about this more, because I don't understand why it is important.  Under the GitHub pages tab in the Settings of the repository, we can just deploy straight from main (or development) without needing to "build".

**Comment by mmsaki** [comment]
I think I read somewhere in the documentation that GitHub pages specify that it should use master for deploying on GitHub pages. But I could be wrong! Obviously haven't this used much, but that was the decision in this. Sometimes it doesn't work when you use other branches, if I find the link to the article I will share it.

**Comment by terrifricker** [comment]
Ah, GitHub has stopped using the word "master" for the default branch.  It is now named "main".  And GitHub pages has been updated to deploy from any branch.  I only learned how to do it during my last voyage and didn't realize it does the "building" behind the scenes.  I thought it was just magic.  I haven't used Actions either.

https://docs.github.com/en/pages/getting-started-with-github-pages/configuring-a-publishing-source-for-your-github-pages-site

**Comment by terrifricker** [comment]
I've never "built" a site.  I have a site ground account and just put my files into the site to make it work.

**Pull request merged**
