### PR TITLE
Feat/17 create initial javascript functionality tf

### LINKED ISSUE #17: Create initial javascript functionality
Create javascript functionality that inserts words from the form into the story template.

### PR DESCRIPTION
**Pull request by terrifricker**
1. Sets constants for the form and story sections
2. Adds event listener to form, listening to "submit" event.
3. On "submit", gather data from form and enter into story.

I'm marking this as a draft pull request.  It won't make sense to merge it until the html is set.  I will make changes to constant declarations once I see the "class" or "id" of the form and story.

### CODE REVIEW

**Comment by AustonBoyd** [comment]
The task is to create JS functionality, but I do not see any code within the JS file...?

**Comment by terrifricker** [comment]
It is in app.js in the development branch.

**Comment by mmsaki** [comment]
hey @terrifricker can you give a demo of how the javascript function works? Maybe next steps on how other members can use it? I having a hard time understanding how the function works. Would be nice to get more details on how to implement it, maybe share youtube documentation on how that function can be used by others correctly. Code comments can also be useful in this case.

**Comment by terrifricker** [comment]
Sure, I'll comment the code.
Here is a demo:
https://codepen.io/terrifricker/pen/wvEjgRR

**Comment by terrifricker** [comment]
I see now, I didn't add .value to the variables in the story.  Because there was no form to test it with, I just entered the javascript and new it would need changing once the other elements were in place.  I see I could have waited, but the other work wasn't getting done.  I thought getting my part done would spur on others.

**Comment by terrifricker** [comment]
I started adding comments, but it's on old code anyway since I've made changes that aren't in the development branch.  I'll add comments in my next iteration.

**Comment by terrifricker** [comment]
I've added comments to my codepen demo:
https://codepen.io/terrifricker/pen/wvEjgRR

**Pull request merged**
